### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by jperelli** [goncy/AFIPizador#1]
![image](https://cloud.githubusercontent.com/assets/1418446/22482942/e7cd5aaa-e7d9-11e6-93fd-3f197437730d.png)

![image](https://cloud.githubusercontent.com/assets/1418446/22483009/3518a4d6-e7da-11e6-96b9-a02ae8ac5f43.png)

**Comment by goncy** [comment]
Ahora lo chusmeo! En que pantalla te pasa? (Adhesion, modificacion o recategorizacion?)

Edit: Afip arreglo la parte de Recategorizacion, Modificacion de datos y Adhesion, por lo que el polyfill ese ya no era necesario, se saco y se subio una nueva version a chrome store, si se encuentran mas errores volvemos a abrir este thread, gracias!

**Comment by jperelli** [comment]
Parecería que no concuerda el código de este repo con la extension publicada en el chrome store, recien la instalé y me sigue apareciendo el mismo error. Y la función abre_actividad parece que no está dentro del código de este github
![image](https://cloud.githubusercontent.com/assets/1418446/22750975/836b70fe-ee11-11e6-86e9-a8ec860aed48.png)

**Comment by goncy** [comment]
Ahora me fijo de resubir la version, no te aparece para actualizar no?

Edit: My bad, me quedo en borrador sin publicar, en unos minutos deberia estar publicada, gracias!

**Comment by jperelli** [comment]
Espectacular, ahí funciona bien ahora.
